FROM ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y curl git && \
    curl -fsSL https://ollama.com/install.sh | sh


# Exposer le port HTTP d’Ollama
EXPOSE 11434

# Dossier par défaut utilisé par Ollama pour les modèles
VOLUME ["/root/.ollama"]

ENTRYPOINT ["ollama-entrypoint.sh"]
