FROM alpine/ollama

ENV DEBIAN_FRONTEND=noninteractive

WORKDIR /app

RUN apk add --no-cache curl

COPY ollama-entrypoint.sh /app/ollama-entrypoint.sh
RUN chmod +x /app/ollama-entrypoint.sh

# Exposer le port HTTP d’Ollama
EXPOSE 11434

# Dossier par défaut utilisé par Ollama pour les modèles
VOLUME ["/root/.ollama"]

ENTRYPOINT ["/app/ollama-entrypoint.sh"]
